### ISSUE TITLE
@everyone @here fix please

### ISSUE THREAD

**Issue by SilverzPlayz** [jackthehack21/MCPEToDiscord#19] opened 2019-08-17 12:35 UTC
**Describe the bug**
players can type @everyone and @here ingame and it pings everyone in discord

**To Reproduce**
Go ingame and do @everyone or @here

**Expected behavior**
For players not he able to @everyone and @here

**Screenshots**
i got none 

**Smartphone (please complete the following information):**
 - Device: IPhone 8

**Pocketmine Version**
Latest
**MCPEToDiscord Version**
latest

**Additional context**
If u make the message  an Embed it wont ping everyone

**Comment by jackthehack21** [comment] 2019-08-17 12:38
Duplicate of #18

**Closed by jackthehack21** 2019-08-17 12:38 UTC
Labels: duplicate
